name: Release and Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  release-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:run

      - name: Build package
        run: npm run build

      - name: List built files
        run: |
          echo "Checking dist directory contents:"
          ls -la dist/ || echo "dist directory not found"
          find . -name "*.js" -path "./dist/*" || echo "No JS files found in dist"

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Release Notes
            
            This release contains various improvements and bug fixes.
            
            For more information, please refer to the commit history and documentation.
          draft: false
          prerelease: false 